#!/usr/bin/env bash

set -o nounset
set -o errexit


echo "Installing pagecache_hit_miss..."
pip install -e .

echo "Installing test libs..."
pip3 install -r requirements/test_requirements.txt
 
echo "Running Flake8 tests..."
flake8 --ignore=E501 pagecache_tools tests 

echo "Running isort check..."
isort --profile black -c pagecache_tools tests


pytest -v -s -rxs tests
